[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
# --- Serveur Web (Axum) ---
axum = "0.7" 
tokio = { version = "1", features = ["full"] }
tower-http = { version = "0.5", features = ["cors"] } # Pour que le frontend puisse te parler

# --- Base de données SQL (Postgres) ---
# Note: J'ai mis "rustls" pour éviter ton erreur d'installation (OpenSSL) précédente
sqlx = { version = "0.7", features = ["runtime-tokio-rustls", "postgres", "uuid", "chrono", "macros"] }

# --- Base de données NoSQL (Mongo) ---
mongodb = "2.8.0"

# --- Données & Utilitaires ---
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.8", features = ["serde", "v4"] }
chrono = { version = "0.4", features = ["serde"] }
dotenvy = "0.15" # Pour lire le fichier .env

# --- Sécurité (Pour plus tard) ---
jsonwebtoken = "9"
bcrypt = "0.15"